/**
 * @fileoverview Jest tests for Sylow Subgroup Construction algorithms.
 * 
 * Tests cover:
 * - Abelian groups (Cyclic, Klein4)
 * - Non-Abelian groups (Symmetric, Alternating, Dihedral, Quaternion)
 * - Trivial cases (Identity, Prime not dividing order)
 * - Correctness of order (Lagrange/Sylow theorem)
 * - Subgroup containment check
 */

import { getSylowSubgroup } from '../src/group-structural-utils.js';
import { 
    createSymmetric, 
    createAlternating, 
    createCyclic, 
    createDihedral, 
    createKleinFour,
    createQuaternion,
    createTrivial 
} from '../src/group-utils.js';
import { isSubgroup } from '../src/group-structural-utils.js';
import { SchreierSimsAlgorithm } from '../src/schreier-sims.js';

// Helper to verify properties of the computed Sylow subgroup
function expectSylowStructure(parentGroup, p, expectedOrder) {
    // 1. Compute Sylow P-Subgroup
    const sylowSubgroup = getSylowSubgroup(parentGroup, p);
    
    // 2. Compute SSA for the result to check order
    const sylowSSA = SchreierSimsAlgorithm.compute(sylowSubgroup);
    
    // 3. Check Order: Must be p^k (maximal power dividing |G|)
    expect(sylowSSA.order).toBe(BigInt(expectedOrder));
    
    // 4. Check Containment: Must be a subgroup of G
    // (Note: This requires group-structural-utils.js)
    expect(isSubgroup(parentGroup, sylowSubgroup)).toBe(true);
}

describe('Sylow Subgroup Algorithm (getSylowSubgroup)', () => {

    // 1. Trivial Case
    test('1. Trivial Group {e}: Sylow-2 should be {e} (Order 1)', () => {
        const G = createTrivial();
        expectSylowStructure(G, 2, 1);
    });

    // 2. Cyclic C2 (Prime Order)
    test('2. Cyclic C2: Sylow-2 should be C2 (Order 2)', () => {
        const G = createCyclic(2);
        expectSylowStructure(G, 2, 2);
    });

    // 3. Prime Not Dividing Order
    test('3. Cyclic C2: Sylow-3 should be {e} (Order 1)', () => {
        const G = createCyclic(2);
        expectSylowStructure(G, 3, 1);
    });

    // 4. Cyclic C6 (Composite Abelian)
    test('4. Cyclic C6: Sylow-2 should have order 2', () => {
        const G = createCyclic(6); // Order 6 = 2 * 3
        expectSylowStructure(G, 2, 2);
    });

    // 5. Cyclic C6 (Composite Abelian)
    test('5. Cyclic C6: Sylow-3 should have order 3', () => {
        const G = createCyclic(6);
        expectSylowStructure(G, 3, 3);
    });

    // 6. Klein Four V4 (Elementary Abelian)
    test('6. Klein Four V4: Sylow-2 should be V4 (Order 4)', () => {
        const G = createKleinFour(); // Order 4 = 2^2
        expectSylowStructure(G, 2, 4);
    });

    // 7. Symmetric S3 (Smallest Non-Abelian) - Sylow 2
    test('7. Symmetric S3: Sylow-2 should have order 2', () => {
        const G = createSymmetric(3); // Order 6 = 2 * 3
        expectSylowStructure(G, 2, 2);
    });

    // 8. Symmetric S3 - Sylow 3
    test('8. Symmetric S3: Sylow-3 should have order 3', () => {
        const G = createSymmetric(3);
        expectSylowStructure(G, 3, 3);
    });

    // 9. Alternating A4 - Sylow 2 (Isomorphic to V4)
    test('9. Alternating A4: Sylow-2 should have order 4', () => {
        const G = createAlternating(4); // Order 12 = 4 * 3
        expectSylowStructure(G, 2, 4);
    });

    // 10. Alternating A4 - Sylow 3
    test('10. Alternating A4: Sylow-3 should have order 3', () => {
        const G = createAlternating(4);
        expectSylowStructure(G, 3, 3);
    });

    // 11. Symmetric S4 - Sylow 2 (Isomorphic to D4)
    test('11. Symmetric S4: Sylow-2 should have order 8', () => {
        const G = createSymmetric(4); // Order 24 = 8 * 3
        expectSylowStructure(G, 2, 8);
    });

    // 12. Symmetric S4 - Sylow 3
    test('12. Symmetric S4: Sylow-3 should have order 3', () => {
        const G = createSymmetric(4);
        expectSylowStructure(G, 3, 3);
    });

    // 13. Dihedral D5 (Order 10)
    test('13. Dihedral D5: Sylow-5 should have order 5', () => {
        const G = createDihedral(5); // Order 10 = 2 * 5
        expectSylowStructure(G, 5, 5);
    });

    // 14. Quaternion Q8 (Non-Abelian p-group)
    test('14. Quaternion Q8: Sylow-2 should be Q8 itself (Order 8)', () => {
        const G = createQuaternion(); // Order 8 = 2^3
        expectSylowStructure(G, 2, 8);
    });

    // 15. Symmetric S5 (Larger Group)
    test('15. Symmetric S5: Sylow-5 should have order 5', () => {
        // |S5| = 120 = 5 * 24. Max power of 5 is 5^1.
        // Sylow-5s are generated by 5-cycles.
        const G = createSymmetric(5);
        expectSylowStructure(G, 5, 5);
    });
});